services:
  - type: web
    name: vidsnap
    runtime: python
    buildCommand: "apt-get install -y ffmpeg || true && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 5000
